---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 2048
  - name: centos-7.3
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    driver:
      network:
        - - private_network
          - ip: 172.16.0.2
    run_list:
      - recipe[apt]
      - recipe[foreman]
      - recipe[foreman::proxy]
    attributes:
      bind:
        masters:
          - 172.16.0.2
        zones:
          nsmaster: ns.foreman.example
          nsmaster_ip: 172.16.0.2
          email: root.foreman.example
      postgresql:
        password:
          postgres: toor
      dhcp:
        interfaces:
          - eth1
      foreman-proxy:
        # FIXME: Register the Smart-Proxy is failing.
        register: false
        dns: true
        dns_interface: eth1
        dhcp:  true
        dhcp_interface: eth1
        dhcp_range: 172.16.0.10 172.16.0.20
