# frozen_string_literal: true

name              'foreman'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides custom resources for installing and configuring Foreman and Foreman Smart Proxy'
source_url        'https://github.com/sous-chefs/foreman'
issues_url        'https://github.com/sous-chefs/foreman/issues'
chef_version      '>= 15.3'
version           '2.0.0'

supports 'debian', '>= 12.0'
supports 'ubuntu', '>= 22.04'

depends 'apache2'
depends 'bind'
depends 'database'
depends 'dhcp'
depends 'hostname'
depends 'hostsfile'
depends 'mysql'
depends 'mysql2_chef_gem'
depends 'postgresql'
depends 'tftp'
