---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@6.0.0
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write

  integration:
    needs: "lint-unit"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - instance: default-debian-12
            suite: default
            platform: debian-12
          - instance: default-ubuntu-2204
            suite: default
            platform: ubuntu-22.04
          - instance: proxy-debian-12
            suite: proxy
            platform: debian-12
          - instance: proxy-ubuntu-2204
            suite: proxy
            platform: ubuntu-22.04
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Cinc Workstation
        uses: sous-chefs/.github/.github/actions/install-workstation@6.0.0
      - name: Run Test Kitchen
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        run: chef exec kitchen test ${{ matrix.instance }} --destroy=always
